### ISSUE TITLE
Specify a range of columns (feature request)

### ISSUE THREAD

**Issue by sjackman** [agordon/datamash#4]
For example

``` sh
datamash sum 1-10
```

**Comment by agordon** [comment]
Hello @sjackman!

Coincidentally, I was just working on this feature (and few others).
They are currently still in the 'devel' branch, not yet merged into master since they need a bit more testing.

You can find it here:
 http://git.savannah.gnu.org/cgit/datamash.git/log/?h=devel
(the 'devel' branch will likely be mirrored in github in few hours automatically).

Or try out the tarball here:
  http://files.housegordon.org/pretest/src/datamash-1.0.7.36-c721.tar.gz

In this version, the following are equivalent:

```
$ seq 9 | paste - - - | datamash sum 1 sum 2 sum 3
12  15  18

$ seq 9 | paste - - - | datamash sum 1,2,3
12  15  18

$ seq 9 | paste - - - | datamash sum 1-3
12  15  18
```

It also has few more operations: `crosstab`, `check`, `round`,`floor`,`ceil`,`trunk`,`frac`,`bin`.
Another small change is support for slightly more verbose but possibly clearer syntax:
`datamash groupby 1,2 sum 3` is equivalent to `datamash -g1,2 sum 3`.
The datamash man-page is updated to include more information and examples about these new features.

Lastly,
I've created a 'bash-completion' script, in `./contrib/bash-completion/datamash` (installed by default to `/usr/local/share/datamash/bash-completion.d/datamash`.
If you source it from the shell (or from `~/.bashrc`), it should help with datamash autocompletion of operations.
regarding homebrew/linuxbrew - I noticed there's a bash completion directory `/usr/local/etc/bash_completion.d/` but I'm not sure if formulae are supposed to put files directly there or not.

Comments and feedback are very welcomed!

  assaf

**Comment by agordon** [comment]
actually, the commit for the improved parsing is already in 'master' (3077dd3e2083e8f30a7c87a787cd62f503e68636), so it might even work with `brew install --HEAD`. but I make no promises...

**Comment by sjackman** [comment]
Fantastic. I look forward to the next stable release. Thanks, @agordon. datamash is a super useful tool. It's my shell equivalent of R's dplyr, which I use a ton. Are you familiar with it?
